@startuml
title GitHub Authorization
Client->GitHub: https://github.com/settings/applications/new(Application name, Homepage URL, Authorization callback URL)
GitHub->OAuthApplication:
OAuthApplication-->Client: show(ID, Secret)
Client->GitHub: `https://github.com/login/oauth/authorize?client_id=$CLIENT_ID&scope=repo`
GitHub-->Client: redirect to Authorization callback URL with query code=${code}
Client->AuthServer: Authorization callback URL with query code=${code}
AuthServer->GitHub:POST https://github.com/login/oauth/access_token ({"code=$CODE","client_id=$ID","client_secret=$SECRET"})
GitHub->AuthServer:response({"access_token":"xxx", "scope":"repo,gist", "token_type":"bearer"})
@enduml
